// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuyaPagos.Infraestructure.Data;

#nullable disable

namespace TuyaPagos.Infraestructure.Migrations
{
    [DbContext(typeof(TuyaPagosContext))]
    [Migration("20220925032252_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TuyaPagos.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("TuyaPagos.Domain.Entities.DetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<int>("Impuesto")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<long>("ValorBruto")
                        .HasColumnType("bigint");

                    b.Property<long>("ValorNeto")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetalleFactura", (string)null);
                });

            modelBuilder.Entity("TuyaPagos.Domain.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Impuesto")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long>("ValorBruto")
                        .HasColumnType("bigint");

                    b.Property<long>("ValorNeto")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Facturas", (string)null);
                });

            modelBuilder.Entity("TuyaPagos.Domain.Entities.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FacturaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("TuyaPagos.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("PorcentajeImpuesto")
                        .HasColumnType("int");

                    b.Property<long>("Precio")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Productos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Tarjeta de crédito",
                            Nombre = "Tarjeta de Crédito Éxito",
                            PorcentajeImpuesto = 19,
                            Precio = 1000L
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Tarjeta de crédito",
                            Nombre = "Tarjeta de Crédito Carulla",
                            PorcentajeImpuesto = 0,
                            Precio = 4000L
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Tarjeta de crédito",
                            Nombre = "Tarjeta de Crédito Alkosto",
                            PorcentajeImpuesto = 10,
                            Precio = 3000L
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Tarjeta de crédito",
                            Nombre = "Tarjeta de Crédito Claro",
                            PorcentajeImpuesto = 10,
                            Precio = 2000L
                        });
                });

            modelBuilder.Entity("TuyaPagos.Domain.Entities.DetalleFactura", b =>
                {
                    b.HasOne("TuyaPagos.Domain.Entities.Factura", "FacturaFk")
                        .WithMany("DetalleFactura")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TuyaPagos.Domain.Entities.Producto", "ProductoFk")
                        .WithMany("DetalleFactura")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacturaFk");

                    b.Navigation("ProductoFk");
                });

            modelBuilder.Entity("TuyaPagos.Domain.Entities.Factura", b =>
                {
                    b.HasOne("TuyaPagos.Domain.Entities.Cliente", "ClienteFk")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClienteFk");
                });

            modelBuilder.Entity("TuyaPagos.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("TuyaPagos.Domain.Entities.Factura", "FacturaFk")
                        .WithMany("Pedidos")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacturaFk");
                });

            modelBuilder.Entity("TuyaPagos.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("TuyaPagos.Domain.Entities.Factura", b =>
                {
                    b.Navigation("DetalleFactura");

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("TuyaPagos.Domain.Entities.Producto", b =>
                {
                    b.Navigation("DetalleFactura");
                });
#pragma warning restore 612, 618
        }
    }
}
